export interface User {
  id: string;
  name: string;
  firstName: string;
  lastName: string;
  email: string;
  pin: string | null;
  profileImage: string;
  coverImage: string[];
  username: string;
  gender: "Male" | "Female" | "Other";
  phoneNumber: string | null;
  bio: string | null;
  dateOfBirth: string | null;
  address: string;
  city: string;
  state: string;
  country: string;
  latitude: number;
  longitude: number;
  earningRate: number;
  userType: "User" | "Admin" | "Other";
  isDriver: boolean;
  hasShop: boolean;
  isOnline: boolean;
  isDeleted: boolean;
  deletedAt: string | null;
  deleteReason: string | null;
  referralCode: string;
  referrerId: string | null;
  rewards: any[];
  refferalPaid: boolean;
  otpCounter: number;
  websocketId: string | null;
  fcmToken: string | null;
  notificationEnabled: boolean;
  reminded: boolean;
  emailVerifiedAt: string | null;
  phoneNumberVerifiedAt: string | null;
  lastMine: string | null;
  lastSeen: string | null;
  createdAt: string;
  updatedAt: string;
  followings: number;
  referralCount?: number;
}